import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/tokyonight-night.toml"
]

[window]

# opacity = 0.8

# padding.x = 10
# padding.y = 10

decorations = "NONE" # "Full"
# decorations_theme_variant = "Dark" # "Light"
option_as_alt = "Both"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 14.0

[env]
TERM = "xterm-256color"

