import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/tokyonight-night.toml"
]

[window]

# opacity = 0.8

# padding.x = 10
# padding.y = 1

decorations = "buttonless" # "NONE" # "Full"
# decorations_theme_variant = "Dark" # "Light"
option_as_alt = "Both"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 14.0

[env]
TERM = "xterm-256color"

